'use client';
import { useEffect, useMemo, useRef } from 'react';
import { Canvas, useFrame, useThree, type ThreeEvent } from '@react-three/fiber';
import { RoundedBox, ContactShadows } from '@react-three/drei';
import * as THREE from 'three';
import { Lamp, Dog, BoxingGloves } from './RoomObjects';
import Lighting from './Lighting';
import Paperclip from './Paperclip';
import Backdrop from './Backdrop';
import type { SkyMode } from '@/lib/daylight';
import { RoomMaterials,Surface,type SurfaceKind } from './Materials';
import Workstation from './Workstation';
import { DetailedBed,DetailedSofa } from './SoftFurnishings';
import CameraRig from './CameraRig';
import InteriorEnvelope from './InteriorEnvelope';
import { windowDimensions } from '@/lib/room-dimensions';
import { EffectComposer,N8AO,ToneMapping,Vignette } from '@react-three/postprocessing';
import { ToneMappingMode } from 'postprocessing';
import { cities, type Focus } from '@/lib/cities';
type Vec=[number,number,number];
type Props={interior:boolean;city:number;focus:Focus;reset:number;onInteract:(f:Focus)=>void;onReady:()=>void;lampOn:boolean;onLampToggle:()=>void;dogReaction:number;onDogClick:()=>void;fortuneCount:number;skyMode:SkyMode;onSkyUnavailable:(unavailable:boolean)=>void};
const palette={wood:'#9a6b45',woodDark:'#503c2e',cream:'#ddd0b7',gold:'#c59e63',wall:'#7d7d76',black:'#242929'};
const woodColors=new Set(['#9a6b45','#503c2e','#a77b52','#93704f','#a07d58','#ab815a','#9e7550','#ad865d','#684d36','#493e32']);
const fabricColors=new Set(['#a89c82','#958e7e','#a39273','#9b8a6a','#a59577','#798071','#c3b497']);
function Box({p,s,c,r=0,rotation,children,...props}:{p:Vec;s:Vec;c:string;r?:number;rotation?:Vec;children?:React.ReactNode;onClick?:(e:ThreeEvent<MouseEvent>)=>void}){const kind:SurfaceKind=woodColors.has(c)?'wood':fabricColors.has(c)?'fabric':c==='#c6c0ae'?'stone':'paint';const radius=r||(s.every(n=>n>.035)?.006:0);return radius?<RoundedBox args={s} radius={radius} smoothness={3} position={p} rotation={rotation} castShadow receiveShadow {...props}><Surface color={c} kind={kind}/>{children}</RoundedBox>:<mesh position={p} rotation={rotation} castShadow receiveShadow {...props}><boxGeometry args={s}/><Surface color={c} kind={kind}/>{children}</mesh>}
function Ball({p,s,c,rotation}:{p:Vec;s:Vec;c:string;rotation?:Vec}){return <mesh position={p} scale={s} rotation={rotation} castShadow receiveShadow><sphereGeometry args={[1,20,12]}/><meshStandardMaterial color={c} roughness={.9}/></mesh>}
function Cylinder({p,r,h,c,rotation}:{p:Vec;r:number;h:number;c:string;rotation?:Vec}){return <mesh position={p} rotation={rotation} castShadow receiveShadow><cylinderGeometry args={[r,r*.94,h,32]}/><Surface color={c} kind={woodColors.has(c)?'wood':'paint'}/></mesh>}
function MemoryWall({click}:{click:()=>void}){return <group position={[-4.88,2.12,-.62]} rotation={[0,Math.PI/2,0]} onClick={e=>{e.stopPropagation();click()}}><Box p={[0,0,-.03]} s={[2.35,1.53,.06]} c="#897958" r={.015}/>{[[-.72,.26,.09],[-.04,.28,-.1],[.67,.21,.05],[-.55,-.4,-.09],[.31,-.38,.07]].map(([x,y,r],i)=><group key={i} position={[x,y,.02]} rotation={[0,0,r]}><Box p={[0,0,.02]} s={[.48,.61,.015]} c={i===3?'#cfb984':'#eee5ce'}/><Box p={[0,.055,.033]} s={[.4,.37,.008]} c={['#707f7a','#a18773','#515f69','#cab789','#8b817a'][i]}/><Box p={[0,.31,.04]} s={[.16,.07,.014]} c="#bca885" rotation={[0,0,-.2]}/>{i!==3&&<><Box p={[-.05,.01,.04]} s={[.04,.16,.01]} c="#dcc5a0"/><Box p={[.07,-.12,.04]} s={[.23,.015,.01]} c="#8d8071"/></>}</group>)}</group>}
function FoodLabel(){const texture=useMemo(()=>{const c=document.createElement('canvas');c.width=256;c.height=128;const ctx=c.getContext('2d')!;ctx.fillStyle='#a52d26';ctx.fillRect(0,0,256,128);ctx.fillStyle='#ffeed5';ctx.textAlign='center';ctx.font='bold 27px Arial';ctx.fillText('PANDA',128,53);ctx.font='21px Arial';ctx.fillText('EXPRESS',128,86);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t},[]);useEffect(()=>()=>texture.dispose(),[texture]);return <mesh position={[-.49,1.395,.171]} rotation={[0,-.24,0]}><planeGeometry args={[.27,.135]}/><meshStandardMaterial map={texture} roughness={.8}/></mesh>}
function Kitchen({click}:{click:()=>void}){return <group position={[2.3,0,2.1]}><Box p={[0,.56,0]} s={[2.15,1.1,.95]} c="#5b665e" r={.02}/><Box p={[0,1.16,0]} s={[2.28,.1,1.05]} c="#c6c0ae" r={.03}/>{[-.69,0,.69].map(x=><Box key={x} p={[x,.66,.49]} s={[.012,.72,.008]} c="#414c43"/>)}<group name="panda-express" position={[-.45,1.22,0]} rotation={[0,-.24,0]} onClick={e=>{e.stopPropagation();click()}}><Box p={[0,.17,0]} s={[.39,.32,.32]} c="#eee5d8" r={.02}/><Box p={[0,.18,.17]} s={[.27,.15,.008]} c="#b33128" r={.018}/><Box p={[0,.355,0]} s={[.43,.025,.35]} c="#efe4d6"/><mesh position={[0,.185,.178]}><circleGeometry args={[.05,24]}/><meshBasicMaterial color="#efe5d0"/></mesh><Box p={[0,.39,0]} s={[.022,.01,.67]} c="#b99062" rotation={[0,-.1,.06]}/><Box p={[.075,.4,0]} s={[.022,.01,.67]} c="#b99062" rotation={[0,.04,-.01]}/></group><Cylinder p={[.52,1.31,.04]} r={.17} h={.17} c="#d3c5a8"/><Ball p={[.52,1.38,.04]} s={[.14,.05,.14]} c="#c78548"/><group onClick={e=>{e.stopPropagation();click()}}><FoodLabel/></group></group>}
function Room({onInteract,lampOn,onLampToggle,dogReaction,onDogClick,fortuneCount,interior}:Props){const window=windowDimensions(interior);return <group>{interior&&<InteriorEnvelope/>}<Box p={[0,-.25,0]} s={[10.3,.5,7.15]} c="#3a403e" r={.045}/><Box p={[0,.01,0]} s={[10,.08,6.95]} c="#a77b52"/>{Array.from({length:25},(_,i)=>{const x=-4.8+i*.4;return <group key={i}>{[-2.32,0,2.32].map((z,j)=><Box key={j} p={[x,.06,z]} s={[.385,.025,2.307]} c={['#93704f','#a07d58','#ab815a','#9e7550','#ad865d'][(i+j*2)%5]}/>)}</group>})}<Box p={[-5,1.7,0]} s={[.18,3.4,7]} c="#b9b9ae"/><Box p={[-4.87,.19,0]} s={[.055,.22,6.9]} c="#aaa48e"/><Box p={[-4.9,3.39,0]} s={[.28,.13,7.05]} c="#bbb19d"/><Box p={[0,window.top+.06,-3.38]} s={[10.2,.15,.32]} c="#c0b49d"/>
  <group onClick={e=>{e.stopPropagation();onInteract('window')}}><Box p={[0,.24,-3.43]} s={[10,.4,.14]} c="#303a3a"/><Box p={[0,window.top,-3.43]} s={[10,.12,.12]} c="#303a3a"/>{[-4.93,-3.28,-1.64,0,1.64,3.28,4.93].map(x=><Box key={x} p={[x,window.center,-3.43]} s={[.06,window.height,.1]} c="#263330"/>)}<mesh position={[0,window.center,-3.48]}><planeGeometry args={[9.87,window.height-.12]}/><meshPhysicalMaterial color="#a7beb9" transparent opacity={.055} roughness={.1} metalness={.2} side={THREE.DoubleSide}/></mesh></group>
  <DetailedBed click={()=>onInteract('bed')}/><Workstation/><MemoryWall click={()=>onInteract('wall')}/><Kitchen click={()=>onInteract('fortune')}/>
  <Box p={[-.7,.1,.65]} s={[3.5,.025,3.7]} c="#a89c82" r={.09}/>{Array.from({length:16},(_,i)=><Box key={i} p={[-2.34+i*.218,.118,.65]} s={[.007,.002,3.55]} c="#958e7e"/>)}
  <DetailedSofa/>
  <group position={[-.55,0,1.55]}><Cylinder p={[0,.46,0]} r={.64} h={.12} c="#684d36"/><Cylinder p={[0,.25,0]} r={.17} h={.42} c="#493e32"/></group>
  <Lamp on={lampOn} toggle={onLampToggle}/><Dog reaction={dogReaction} click={onDogClick}/><BoxingGloves click={()=>onInteract('gloves')}/><Paperclip count={fortuneCount} click={()=>onInteract('paperclip')}/>
 </group>}
function Markers({nodes,visible}:{nodes:React.RefObject<(HTMLButtonElement|null)[]>;visible:boolean}){const {size,camera}=useThree();const positions=useMemo(()=>[new THREE.Vector3(-4.5,2.95,-.6),new THREE.Vector3(-.55,1.2,1.55),new THREE.Vector3(1.85,1.95,2.1)],[]);const point=useMemo(()=>new THREE.Vector3(),[]);useFrame(()=>{positions.forEach((p,i)=>{const node=nodes.current[i];if(!node)return;point.copy(p).project(camera);node.style.transform='translate(-50%,-50%) translate('+((point.x*.5+.5)*size.width)+'px,'+((-point.y*.5+.5)*size.height)+'px)';node.style.visibility=visible&&point.z<1?'visible':'hidden'})});return null}
export default function Scene(props:Props){const nodes=useRef<(HTMLButtonElement|null)[]>([]);return <><Canvas camera={{position:[4.4,2.35,5.4],fov:59,near:.08,far:100}} shadows={{type:THREE.PCFShadowMap}} dpr={[1,1.6]} gl={{antialias:true,alpha:true,powerPreference:'high-performance'}} fallback={<div className="loading"><p>Your browser needs WebGL to enter the penthouse.</p></div>}><Lighting onReady={props.onReady} lampOn={props.lampOn} skyMode={props.skyMode}/><CameraRig focus={props.focus} reset={props.reset} interior={props.interior}/><RoomMaterials><Room {...props}/></RoomMaterials><Backdrop interior={props.interior} city={props.city} mode={props.skyMode} onUnavailable={props.onSkyUnavailable}/><Markers nodes={nodes} visible={props.focus==='home'}/><ContactShadows position={[0,-.54,0]} opacity={.36} scale={25} blur={2.5} far={5} resolution={256} frames={1}/><EffectComposer multisampling={0}><N8AO aoRadius={.35} distanceFalloff={1.1} intensity={1.4} quality="low" halfRes/><ToneMapping mode={ToneMappingMode.ACES_FILMIC}/><Vignette offset={.3} darkness={.22}/></EffectComposer></Canvas><div className="scene-hotspots"><button ref={n=>{nodes.current[0]=n}} className="hotspot" onClick={()=>props.onInteract('wall')}><span>+</span> Our wall</button><button ref={n=>{nodes.current[1]=n}} className="hotspot" onClick={()=>props.onInteract('gloves')}><span>+</span> Boxing gloves</button><button ref={n=>{nodes.current[2]=n}} className="hotspot" onClick={()=>props.onInteract('fortune')}><span>+</span> Fortune cookie</button></div></>}
