'use client';
import { useEffect,useRef,useState } from 'react';
import { Eraser, RotateCcw, Download, Play, Check } from 'lucide-react';
import { supabase,uploadImage } from '@/lib/supabase';
const prompts=['Panda Express','Tokyo','Your dream apartment','A ridiculous date','A dog','Your future','Draw me'];
const colors=['#28343c','#b55240','#d9a441','#67826b','#7397b3'];
type Point={x:number;y:number};type Stroke={points:Point[];color:string;width:number};
export default function DrawGame(){const canvas=useRef<HTMLCanvasElement>(null),drawing=useRef(false),strokes=useRef<Stroke[]>([]),current=useRef<Stroke|null>(null);const [color,setColor]=useState(colors[0]),[width,setWidth]=useState(5),[prompt,setPrompt]=useState(''),[remaining,setRemaining]=useState(60),[running,setRunning]=useState(false),[message,setMessage]=useState(''),[guess,setGuess]=useState(''),[hidden,setHidden]=useState(false),[saving,setSaving]=useState(false);const end=useRef(0);
 function paint(){const ctx=canvas.current?.getContext('2d');if(!ctx)return;ctx.fillStyle='#f7f2e8';ctx.fillRect(0,0,900,500);for(const stroke of [...strokes.current,...(current.current?[current.current]:[])]){ctx.beginPath();ctx.strokeStyle=stroke.color;ctx.lineWidth=stroke.width;ctx.lineCap='round';ctx.lineJoin='round';stroke.points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));if(stroke.points.length===1){const p=stroke.points[0];ctx.lineTo(p.x+.01,p.y+.01)}ctx.stroke()}}
 useEffect(()=>paint(),[]);useEffect(()=>{if(!running)return;const t=setInterval(()=>{const left=Math.max(0,Math.ceil((end.current-Date.now())/1000));setRemaining(left);if(left===0){setRunning(false);drawing.current=false;setMessage('Pencils down. Time to guess.')}},200);return()=>clearInterval(t)},[running]);
 function start(){strokes.current=[];current.current=null;paint();setPrompt(prompts[Math.floor(Math.random()*prompts.length)]);setGuess('');setMessage('');setHidden(false);setRemaining(60);end.current=Date.now()+60000;setRunning(true)}
 function point(e:React.PointerEvent<HTMLCanvasElement>){const r=e.currentTarget.getBoundingClientRect();return{x:(e.clientX-r.left)*900/r.width,y:(e.clientY-r.top)*500/r.height}}
 function finish(){if(current.current){strokes.current.push(current.current);current.current=null}drawing.current=false;paint()}
 function download(){const a=document.createElement('a');a.href=canvas.current!.toDataURL('image/png');a.download=`penthouse-22-${prompt||'masterpiece'}.png`;a.click()}
 async function save(){if(!supabase){setMessage('The shared gallery isn’t connected yet. You can download your masterpiece instead.');return}setSaving(true);try{const blob=await new Promise<Blob|null>(r=>canvas.current!.toBlob(r,'image/png'));if(!blob)throw Error('Could not prepare the drawing.');const path=await uploadImage(blob,'drawing');const {data:{user}}=await supabase.auth.getUser();const {error}=await supabase.from('drawings').insert({prompt,created_by:user!.id,image_url:path});if(error)throw error;setMessage('A masterpiece, officially archived.')}catch(e){setMessage((e as Error).message)}finally{setSaving(false)}}
 return <section className="draw-game"><p className="connection-note">Pass-and-play practice · Online rooms will open when the private connection is set up.</p><div className="draw-header"><div><span className="eyebrow">YOUR PROMPT</span><h3>{!prompt?'Ready, artist?':hidden?'No peeking.':prompt}</h3></div><div className={`timer ${remaining<10?'timer-low':''}`}>{remaining}<small>SECONDS</small></div></div><div className="drawing-tools"><div>{colors.map(c=><button key={c} className="swatch" aria-label={`Pencil ${c}`} aria-pressed={color===c} style={{background:c}} onClick={()=>setColor(c)}/>)}</div><button title="Eraser" aria-label="Eraser" aria-pressed={color==='#f7f2e8'} onClick={()=>setColor('#f7f2e8')}><Eraser size={17}/></button><label>Brush<input type="range" aria-label="Brush size" min={2} max={24} value={width} onChange={e=>setWidth(+e.target.value)}/></label><button aria-label="Clear canvas" onClick={()=>{strokes.current=[];current.current=null;paint()}}><RotateCcw size={17}/></button></div><canvas ref={canvas} className="drawing-canvas" width={900} height={500} aria-label="Drawing canvas" onPointerDown={e=>{if(!running)return;e.currentTarget.setPointerCapture(e.pointerId);drawing.current=true;current.current={color,width,points:[point(e)]};paint()}} onPointerMove={e=>{if(!drawing.current||!running)return;current.current?.points.push(point(e));paint()}} onPointerUp={finish} onPointerCancel={finish}/><div className="game-actions"><button className="gold-button" onClick={start}><Play size={15}/>{prompt?'New round':'Start drawing'}</button>{running&&<button className="secondary-button" onClick={()=>{finish();setRunning(false);setHidden(true)}}>Done · pass it over</button>}{prompt&&!running&&<><button className="secondary-button" onClick={download}><Download size={15}/>Download</button><button className="secondary-button" disabled={saving} onClick={save}>Save to Our Art</button></>}</div>{prompt&&!running&&<form className="guess-form" onSubmit={e=>{e.preventDefault();const normalize=(s:string)=>s.toLowerCase().replace(/[^a-z0-9]/g,'');setMessage(normalize(guess)===normalize(prompt)?'Correct! A truly visionary work of art.':`Honestly, I don’t know what that was either. It was “${prompt}”.`);setHidden(false)}}><input aria-label="Your guess" value={guess} required onChange={e=>setGuess(e.target.value)} placeholder="What is it?"/><button className="gold-button">Guess</button></form>}<p className="game-message" role="status">{message}</p></section>
}
