'use client';
import { useEffect,useRef,useState } from 'react';
type Fighter={x:number;y:number;vy:number;hp:number;attack:number;cooldown:number;facing:number};
export default function MiniFighter(){const canvas=useRef<HTMLCanvasElement>(null),keys=useRef(new Set<string>()),state=useRef<{p:Fighter;e:Fighter;time:number}|null>(null),[character,setCharacter]=useState('Jia'),[playing,setPlaying]=useState(false),[result,setResult]=useState('');
 function start(){state.current={p:{x:180,y:0,vy:0,hp:100,attack:0,cooldown:0,facing:1},e:{x:580,y:0,vy:0,hp:100,attack:0,cooldown:0,facing:-1},time:60};setResult('');setPlaying(true);keys.current.clear()}
 useEffect(()=>{const down=(e:KeyboardEvent)=>{if(['ArrowLeft','ArrowRight','ArrowUp',' ','a','d','w','j'].includes(e.key)){e.preventDefault();keys.current.add(e.key)}};const up=(e:KeyboardEvent)=>keys.current.delete(e.key);const blur=()=>keys.current.clear();if(playing){addEventListener('keydown',down);addEventListener('keyup',up);addEventListener('blur',blur)}return()=>{removeEventListener('keydown',down);removeEventListener('keyup',up);removeEventListener('blur',blur)}},[playing]);
 useEffect(()=>{if(!playing)return;let id=0,last=0,aiClock=0;function frame(now:number){const dt=last?Math.min((now-last)/1000,.04):0;last=now;const s=state.current!,ctx=canvas.current!.getContext('2d')!;s.time-=dt;const p=s.p,e=s.e,held=keys.current;p.facing=p.x<e.x?1:-1;e.facing=-p.facing;if(held.has('ArrowLeft')||held.has('a'))p.x-=210*dt;if(held.has('ArrowRight')||held.has('d'))p.x+=210*dt;if((held.has('ArrowUp')||held.has('w'))&&p.y===0)p.vy=430;if((held.has(' ')||held.has('j'))&&p.cooldown<=0){p.attack=.2;p.cooldown=.45;if(Math.abs(p.x-e.x)<85&&Math.abs(p.y-e.y)<65)e.hp-=10}aiClock+=dt;if(Math.abs(p.x-e.x)>65)e.x+=e.facing*140*dt;if(aiClock>1.05){aiClock=0;if(Math.abs(p.x-e.x)<90&&Math.abs(p.y-e.y)<65){e.attack=.2;p.hp-=8}if(p.y>20&&e.y===0)e.vy=390}for(const f of [p,e]){f.x=Math.max(40,Math.min(760,f.x));f.y=Math.max(0,f.y+f.vy*dt);f.vy-=980*dt;if(f.y===0)f.vy=0;f.attack=Math.max(0,f.attack-dt);f.cooldown-=dt}ctx.fillStyle='#192630';ctx.fillRect(0,0,800,350);ctx.strokeStyle='#ffffff09';for(let x=0;x<800;x+=40){ctx.beginPath();ctx.moveTo(x,90);ctx.lineTo(x,300);ctx.stroke()}ctx.fillStyle='#283a42';ctx.fillRect(0,294,800,56);ctx.fillStyle='#cca878';ctx.fillRect(0,294,800,2);function person(f:Fighter,color:string,label:string){const y=294-f.y;ctx.fillStyle='#0004';ctx.beginPath();ctx.ellipse(f.x,299,32,6,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle=color;ctx.lineWidth=12;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(f.x-10,y-3);ctx.lineTo(f.x-9,y-28);ctx.lineTo(f.x,y-55);ctx.lineTo(f.x+12,y-28);ctx.lineTo(f.x+14,y-3);ctx.stroke();ctx.fillStyle=color;ctx.fillRect(f.x-17,y-79,34,40);ctx.fillStyle='#ddbd96';ctx.beginPath();ctx.arc(f.x,y-94,18,0,Math.PI*2);ctx.fill();ctx.fillStyle='#363439';ctx.beginPath();ctx.arc(f.x,y-100,18,Math.PI,Math.PI*2);ctx.fill();ctx.strokeStyle=color;ctx.beginPath();ctx.moveTo(f.x,y-69);ctx.lineTo(f.x+f.facing*(f.attack>0?65:29),y-(f.attack>0?65:54));ctx.stroke();ctx.fillStyle='#f0dcba';ctx.font='12px Arial';ctx.textAlign='center';ctx.fillText(label,f.x,y-124)}person(p,'#c9a06e',character);person(e,'#85a19a',character==='Jia'?'Ryan':'Jia');ctx.fillStyle='#34434a';ctx.fillRect(25,28,280,10);ctx.fillRect(495,28,280,10);ctx.fillStyle='#c9a06e';ctx.fillRect(25,28,280*Math.max(p.hp,0)/100,10);ctx.fillStyle='#85a19a';ctx.fillRect(495,28,280*Math.max(e.hp,0)/100,10);ctx.fillStyle='#eee0c8';ctx.font='24px Georgia';ctx.textAlign='center';ctx.fillText(String(Math.max(0,Math.ceil(s.time))),400,43);if(p.hp<=0||e.hp<=0||s.time<=0){const who=p.hp===e.hp?'A diplomatic draw.':p.hp>e.hp?`${character} wins. Absolutely devastating.`:`${character==='Jia'?'Ryan':'Jia'} wins. We don’t have to talk about it.`;setResult(who);setPlaying(false);return}id=requestAnimationFrame(frame)}id=requestAnimationFrame(frame);return()=>cancelAnimationFrame(id)},[playing,character]);
 return <section className="fighter"><p className="panel-description">A friendly dispute. Very tiny fists.</p><div className="type-selector">{['Jia','Ryan'].map(c=><button disabled={playing} aria-pressed={character===c} key={c} onClick={()=>setCharacter(c)}>Play as {c}</button>)}</div><div className="fighter-arena"><canvas ref={canvas} width={800} height={350} aria-label="Mini fighter arena"/>{!playing&&<div className="fighter-overlay"><p>{result||'Choose your fighter.'}</p><button className="gold-button" onClick={start}>{result?'Rematch':'Let’s settle this'}</button></div>}</div><div className="touch-controls">{[['ArrowLeft','←'],['ArrowRight','→'],['ArrowUp','Jump'],[' ','Attack']].map(([k,label])=><button key={k} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);keys.current.add(k)}} onPointerUp={()=>keys.current.delete(k)} onPointerCancel={()=>keys.current.delete(k)}>{label}</button>)}</div><p className="control-help">← → Move · ↑ Jump · Space Attack</p></section>
}
