export const fortunes = [
  'The best view in this apartment is the person you share it with.',
  'A very good day is waiting on the other side of a very good nap.',
  'Somewhere in your future, the takeout is still warm and the company is perfect.',
  'Your next great adventure may begin with “what should we eat?”',
  'One room. Many cities. You are the constant worth keeping.',
  'A small white dog has reviewed your plans and approves of the snacks.',
  'You do not have to earn a quiet evening.',
  'The keys to something wonderful are already in your pocket.',
  'Today is a good day to be ridiculously fond of someone.',
  'Some dreams arrive as grand entrances. Others arrive wearing your hoodie.',
  'Your future contains a kitchen with excellent late-night conversation.',
  'A window can change the view. A person can change the whole room.',
  'The next chapter has room for both ambition and breakfast in bed.',
  'You are allowed to build a life that feels good on an ordinary Tuesday.',
  'A spectacular skyline pairs well with completely unspectacular plans.',
  'Your table will never be too small for one more story.',
  'There is no dress code for being loved.',
  'Something lovely will happen while you are looking for your charger.',
  'The most valuable thing you bring home is yourself.',
  'A future worth having makes space for a little silliness.',
  'Tokyo is patiently saving a tiny restaurant for your future selves.',
  'New York has a million windows. You only need one good view together.',
  'Paris recommends taking the long way back after dinner.',
  'Taipei has a night-market detour with your names on it.',
  'you can just do things - Sam Altman who quoted someone else',
  'Your next favorite city might be the one where you lose track of time.',
  'A map is only a suggestion when the company is this good.',
  'Pack a little lighter. Leave room for the stories.',
  'The best souvenir will be a joke nobody else understands.',
  'A missed train may introduce you to a much better afternoon.',
  'There is a rooftop somewhere that will feel like yours.',
  'The airport goodbye is temporary. The next hello is already on its way.',
  'A very ordinary street will become special because you walked it together.',
  'Your dream apartment can have more than one address.',
  'Someday, “one day” will quietly become “remember when.”',
  'A new city is an excellent excuse to order a second dessert.',
  'Make something people want.  - YC',
  'The scenic route is still a route.',
  'Some of the best reservations are the ones you forget to make.',
  'The horizon has not run out of possibilities.',
  'Orange chicken is a perfectly respectable love language.',
  'Your next big decision can wait until after lunch.',
  'A shared last dumpling is a very small act of heroism.',
  'The universe suggests extra sauce.',
  'Dinner does not need to be impressive to be worth remembering.',
  'There is wisdom in ordering enough for tomorrow.',
  'The right person will remember which bite you wanted.',
  'A kitchen dance break improves almost every recipe.',
  'Your finest meal this week may come in a paper container.',
  'Do not underestimate the emotional importance of noodles.',
  'get me more jasmine tea drinks',
  'Good fortune favors the person who brings fries to share.',
  'Someone is going to steal a bite of your food. You may secretly enjoy this.',
  'The second cup of tea is for staying a little longer.',
  'You are one grocery trip away from an unnecessarily elaborate breakfast.',
  'A midnight sandwich can be a tiny celebration.',
  'The answer to “should we get dessert?” has been approved unanimously.',
  'A full fridge is nice. A person who feeds you is nicer.',
  'A new favorite dish is hiding just outside your usual order.',
  'This cookie recommends a meal that requires absolutely no washing up.',
  'The dog has contributed nothing to rent and everything to morale.',
  'A wagging tail is a very convincing argument for coming home early.',
  'Someone with four paws believes you are already successful.',
  'Your smallest roommate has the largest claim on the soft blanket.',
  'Take some time to rest. you work hard',
  'The dog is not judging your life choices. Only your portion sizes.',
  'A short walk may solve what a long meeting could not.',
  'Your next audience may consist of one very attentive white dog.',
  'The best alarm clock sometimes has a cold nose.',
  'There is room in the plan for an unexpected game of fetch.',
  'The dog would like this fortune converted into a treat.',
  'A nap beside a sleeping animal counts as quality time.',
  'Someone is practicing their excited greeting for you right now.',
  'Good news: the household cuddle quota has not been met.',
  'A paw on your knee is a reminder to take the break.',
  'The dog has decided that your personal space is a shared resource.',
  'Your slippers may go missing. Your welcome home will not.',
  'A little mischief keeps a beautiful apartment interesting.',
  'The dog requests fewer emails and more floor time.',
  'You have been promoted to Chief Belly Rub Officer.',
  'Love is sometimes just someone moving over to make room.',
  'The little things are doing most of the important work.',
  'You can be completely yourself and still be someone’s favorite person.',
  'A good hug can make the rest of the day feel negotiable.',
  'There is a person who would choose your ordinary days, too.',
  'The right kind of closeness leaves room to breathe.',
  'A silly voice may become a cherished family tradition.',
  'Some conversations are better with the lights low and no deadline.',
  'A soft landing is a beautiful thing to be for someone.',
  'You do not have to say something brilliant. You can simply stay.',
  'An inside joke is a small home you can carry anywhere.',
  'Someone’s favorite notification might be your name.',
  'A hand reached across the table can say the whole thing.',
  'Being understood is an underrated kind of luxury.',
  'Your laugh improves the acoustics of every room.',
  'A little patience can turn a difficult evening into a shared story.',
  'The best plans make room for changing your mind together.',
  'It is okay to ask for a longer hug.',
  'A comfortable silence is something worth finding.',
  'You deserve affection that does not require a performance.',
  'You can be proud of how far you have come and still want more.',
  'The next small step is allowed to be very small.',
  'Rest is part of the plan, not a departure from it.',
  'A difficult day does not get to define the whole year.',
  'You have solved unfamiliar things before. This is another beginning.',
  'Your pace does not need to match anyone else’s.',
  'An unfinished list can wait beside a finished cup of tea.',
  'You are growing even when the progress refuses to be dramatic.',
  'Ask the question. It might open a better door.',
  'A fresh start can happen at 3:17 in the afternoon.',
  'Your worth does not clock out when your productivity does.',
  'There is strength in letting someone help.',
  'One brave sentence can change a conversation.',
  'You are allowed to leave room in your calendar for joy.',
  'A detour is not proof that you are lost.',
  'The version of you who kept going deserves a little credit.',
  'Not every opportunity deserves your evening.',
  'The answer may arrive after you stop staring at the screen.',
  'Something you find easy may be exactly what someone else needs.',
  'A good life is built from more than impressive days.',
  'Tonight’s forecast: lower lights and fewer obligations.',
  'A clean pillowcase is a small but legitimate fresh start.',
  'Your phone can take a break before you do.',
  'The lamp is on. You do not need another reason to stay in.',
  'A rainy evening is an invitation to cancel nothing, because you made no plans.',
  'The softest blanket deserves its own place in your schedule.',
  'Take your shoes off. You have arrived somewhere kind.',
  'A favorite song may be waiting to improve this exact moment.',
  'You are allowed to watch the city without joining its hurry.',
  'Open the window in your mind. Let an old worry leave.',
  'A slow morning is not a wasted morning.',
  'Tonight does not have to become a story. It can just be nice.',
  'Something about warm socks makes a problem less persuasive.',
  'The dishes will survive a five-minute dance break.',
  'Your best idea may visit while you are doing absolutely nothing.',
  'A room can feel like a deep breath.',
  'Let the day end before you start tomorrow.',
  'Your future self appreciates the glass of water beside the bed.',
  'A little less scrolling may leave room for a little more living.',
  'You may borrow tomorrow’s ambition. Keep tonight’s peace.',
  'The gloves are small. The bragging rights are enormous.',
  'A rematch is a valid form of optimism.',
  'Winning is nice. Having someone fun to lose to is rarer.',
  'Your next victory may be remembering where you left your keys.',
  'A dramatic victory speech is permitted for very minor achievements.',
  'Good sportsmanship includes pretending that was definitely intentional.',
  'A tiny competition can make an ordinary evening memorable.',
  'The referee is a dog and can probably be bribed.',
  'You have excellent odds of laughing before this game is over.',
  'A well-timed joke can be your strongest move.',
  'The true champion remembers to pause for snacks.',
  'There is no leaderboard for being pleasantly ridiculous.',
  'You are one playful challenge away from a better mood.',
  'Your opponent may also be your favorite person. Complicated, but manageable.',
  'A friendly rivalry is just affection wearing boxing gloves.',
  'A comeback story looks good on you.',
  'Celebrate the little win. Use the fancy voice.',
  'Laughter remains undefeated.',
  'Nobody remembers the score as clearly as the fun.',
  'An excellent evening can begin with “bet you can’t.”',
  'Twenty-two floors up, there is still room to grow.',
  'A birthday is a good excuse to want something wonderful.',
  'The year ahead does not need to look like the year behind.',
  'You are not late to the life that fits you.',
  'Your next favorite memory has not happened yet.',
  'Make a wish that belongs to you, even if it sounds a little ambitious.',
  'The candles are temporary. The people cheering for you are the gift.',
  'You are allowed to celebrate simply being here.',
  'This next chapter could use more photos with you actually in them.',
  'An ordinary day may turn out to be the beginning of everything.',
  'There is time to learn another favorite thing about yourself.',
  'A dream can change shape and still be worth following.',
  'A future home begins with noticing what makes you feel at home now.',
  'You have not met every place where you will feel happy.',
  'A little courage travels farther when it has good company.',
  'The best part of growing up may be choosing your own kind of fun.',
  'Take a picture of something you will be glad to remember.',
  'A new tradition can start with something as small as this cookie.',
  'There will be more reasons to celebrate than you can predict.',
  'Keep a little room in the future for being surprised.',
  'A note saved today may be exactly what you need another day.',
  'Small kindnesses have an excellent memory.',
  'The paper clip is doing important emotional infrastructure work.',
  'You can collect beautiful moments without making them perfect.',
  'A few good words are worth keeping within reach.',
  'There is probably a compliment you have forgotten to believe.',
  'Your next good story may start with a very bad idea for dinner.',
  'The best sort of wealth is having someone to tell the little things to.',
  'Leave a light on for the version of you who needs a gentler evening.',
  'A generous interpretation can change the whole conversation.',
  'Notice the good thing while it is happening.',
  'You do not need a special occasion to write a kind sentence.',
  'A tiny note can travel farther than a grand speech.',
  'Something familiar can become lovely again when you slow down.',
  'There is a good reason to look up from your phone right now.',
  'The next five minutes can still become your favorite part of today.',
  'Keep the memory. Let the awkward part become the funny part.',
  'You are making a life, not just getting through a schedule.',
  'A warm room and a person who is glad you are here: that is a kind of fortune.',
  'When the last cookie is opened, there will still be more good things ahead.',
  // Append new fortunes so previously saved note IDs keep their original words.
  'johnisgay',
  'so buns',
  'just be a chiller',
  'ur racist',
  'ur my little cute chud',
  'just take a walk in the tenderloin',
  'combine the future of medicine and ai',
  'ur the soma tweaker',
  'stussy makes you a socal abb',
  'Jia is thinking of you',
  'remember to rest <3',
  'you will meet a girl and sleep on the floor',
  'you need a haircut',
  "I'm your dictator",
] as const;

export type SavedFortune = { id: number; openedAt: string };

// Preserve historical IDs. Explicitly removed notes are hidden from both
// future draws and the paper clip, without deleting anyone else's saved notes.
export const removedFortuneIds = new Set([10,16,66,76,126,132,138,140,152,156,168,172]);
export function isVisibleFortune(id:number){return Number.isInteger(id)&&id>=0&&id<fortunes.length&&!removedFortuneIds.has(id)}
// Replace one generic in each group of 20 without changing historical text IDs.
export const personalFortuneIds = Array.from({length:5},(_,index)=>209+index);
export const genericFortuneIds = Array.from({length:100},(_,index)=>index%20===19?personalFortuneIds[Math.floor(index/20)]:index*2).filter(isVisibleFortune);
export const jokeFortuneIds = Array.from({length:9},(_,index)=>200+index);
export const activeFortuneIds = [...genericFortuneIds,...jokeFortuneIds];
export const fortunePoolSize = activeFortuneIds.length;
export type FortuneKind = 'generic'|'joke';
export function fortuneKindForOpening(number:number):FortuneKind {
 return number>=2&&(number-2)%12===0?'joke':'generic';
}
