import assert from 'node:assert/strict';
import {chromium} from '@playwright/test';
import sharp from 'sharp';
import * as THREE from 'three';
const browser=await chromium.launch({channel:'msedge',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const errors=[];
try{
 const context=await browser.newContext({viewport:{width:1440,height:1000}});
 await context.addInitScript(()=>{window.barkStarts=0;const start=AudioBufferSourceNode.prototype.start;AudioBufferSourceNode.prototype.start=function(...args){window.barkStarts++;return start.apply(this,args)}});
 const page=await context.newPage();
 page.on('pageerror',e=>errors.push(e.message));
 page.on('console',e=>{if(e.type()==='error')errors.push(e.text())});
 await page.goto('http://127.0.0.1:3023',{waitUntil:'networkidle',timeout:90000});
 const canvas=page.locator('.scene-layer canvas');await canvas.waitFor();await page.waitForTimeout(4000);
 await page.getByRole('button',{name:'Room overview',exact:true}).click();await page.waitForTimeout(3500);
 const lamp=()=>page.getByRole('button',{name:/Turn the lamp/});
 assert.equal(await lamp().getAttribute('aria-pressed'),'true');
 const lit=await page.screenshot({path:'preview-room-on.png'});
 async function objectClick(position){const bounds=await canvas.boundingBox();const camera=new THREE.OrthographicCamera(-bounds.width/2,bounds.width/2,bounds.height/2,-bounds.height/2,.1,100);camera.position.set(11,9,14);camera.lookAt(-2,.55,0);camera.zoom=Math.min(bounds.width/17,100);camera.updateProjectionMatrix();camera.updateMatrixWorld();const point=new THREE.Vector3(...position).project(camera);await page.mouse.click(bounds.x+(point.x*.5+.5)*bounds.width,bounds.y+(-point.y*.5+.5)*bounds.height)}
 await objectClick([-.45,2.18,-2.65]);await page.waitForTimeout(1600);
 assert.equal(await lamp().getAttribute('aria-pressed'),'false','clicking the physical lamp must work');
 const dark=await page.screenshot({path:'preview-room-off.png'});
 const brightness=async buffer=>(await sharp(buffer).stats()).channels.slice(0,3).reduce((sum,c)=>sum+c.mean,0)/3;
 const on=await brightness(lit),off=await brightness(dark);assert(on-off>5,'room must visibly dim');console.log('Brightness on/off',on,off);
 await lamp().click();
 await objectClick([.5,.5,2.78]);await page.waitForTimeout(500);
 assert.equal(await page.evaluate(()=>window.barkStarts),0,'dog clicks stay silent');
 await objectClick([-.55,.8,1.55]);await page.getByRole('dialog').waitFor();
 await page.getByRole('button',{name:'Let’s settle this'}).click();await page.keyboard.press('Space');await page.keyboard.press('Escape');await page.waitForTimeout(3500);
 assert.equal(await page.getByText(/Draw something|Our art/i).count(),0);
 await objectClick([1.85,1.57,2.1]);await page.getByRole('dialog').waitFor();
 await page.getByText('Saved to your shared paper clip.',{exact:true}).waitFor();
 const first=await page.locator('.fortune-number').innerText();await page.screenshot({path:'preview-fortune.png'});
 await page.getByRole('button',{name:'One more cookie'}).click();await page.getByText('Saved to your shared paper clip.',{exact:true}).waitFor();
 await page.waitForFunction(previous=>document.querySelector('.fortune-number')?.textContent!==previous,first);
 const second=await page.locator('.fortune-number').innerText();assert.notEqual(first,second);
 await page.getByRole('button',{name:/Your notes/}).click();await page.locator('.fortune-collection').waitFor();
 const notes=await page.locator('.fortune-collection .fortune-slip').count();assert(notes>=2);
 await page.screenshot({path:'preview-paperclip.png'});
 await page.keyboard.press('Escape');await page.waitForTimeout(3500);await objectClick([3.03,1.3,1.83]);await page.locator('.fortune-collection').waitFor();
 await page.keyboard.press('Escape');await page.getByRole('button',{name:'Taipei',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Taipei',exact:true}).getAttribute('aria-pressed'),'true');
 await context.close();
 const other=await browser.newContext({viewport:{width:390,height:844}}),mobile=await other.newPage();
 await mobile.goto('http://127.0.0.1:3023',{waitUntil:'networkidle',timeout:90000});await mobile.waitForTimeout(3500);await mobile.screenshot({path:'preview-room-mobile.png'});
 assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'mobile overflow');
 await mobile.getByRole('button',{name:'Paper clip · saved fortunes'}).click();await mobile.locator('.fortune-collection').waitFor();
 assert.equal(await mobile.locator('.fortune-collection .fortune-slip').count(),notes,'a fresh device must see the same collection');
 await mobile.reload({waitUntil:'networkidle'});await mobile.getByRole('button',{name:'Paper clip · saved fortunes'}).click();await mobile.locator('.fortune-collection').waitFor();assert.equal(await mobile.locator('.fortune-collection .fortune-slip').count(),notes);
 assert.deepEqual(errors,[]);console.log('PASS: physical lamp/dog/gloves/Panda clicks, silent dog, fighter, shared fortunes, mobile, reload persistence; no browser errors.');
}finally{await browser.close()}
