import {chromium} from '@playwright/test';
const browser=await chromium.launch({channel:'msedge',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
const errors=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('console',e=>{if(e.type()==='error')errors.push(e.text())});
await page.goto('http://127.0.0.1:3022',{waitUntil:'networkidle',timeout:90000});
await page.locator('.scene-layer canvas').waitFor({timeout:90000});
await page.waitForTimeout(5000);
console.log('Canvas',await page.locator('.scene-layer canvas').evaluate(c=>({width:c.width,height:c.height,rect:{width:c.getBoundingClientRect().width,height:c.getBoundingClientRect().height},context:!!c.getContext('webgl2')})));
await page.screenshot({path:'preview-desktop.png'});
await page.getByRole('button',{name:'Paris',exact:true}).click();
await page.waitForTimeout(1300);
if(await page.getByRole('button',{name:'Paris',exact:true}).getAttribute('aria-pressed')!=='true')throw Error('City selection did not update');
await page.getByRole('button',{name:'Reset the view'}).click();
await page.locator('.room-actions').getByRole('button',{name:'Our wall'}).click();
await page.getByRole('dialog').waitFor();
await page.getByRole('button',{name:'Pin something'}).click();
await page.getByRole('textbox',{name:'A little title'}).fill('A little test');
await page.getByRole('textbox',{name:'Your words'}).fill('A future memory.');
await page.keyboard.press('Escape');
await page.locator('.room-actions').getByRole('button',{name:'The arcade'}).click();
await page.getByRole('dialog').waitFor();
await page.getByRole('button',{name:/Draw something/}).click();
await page.getByRole('button',{name:'Start drawing'}).click();
const box=await page.locator('.drawing-canvas').boundingBox();
await page.mouse.move(box.x+50,box.y+50);await page.mouse.down();await page.mouse.move(box.x+150,box.y+150,{steps:12});await page.mouse.up();
await page.getByRole('button',{name:'Done · pass it over'}).click();
await page.screenshot({path:'preview-drawing.png'});
await page.getByRole('button',{name:'Back to the arcade'}).click();
await page.getByRole('button',{name:/Mini fighter/}).click();
await page.getByRole('button',{name:'Let’s settle this'}).click();
await page.keyboard.down('ArrowRight');await page.waitForTimeout(900);await page.keyboard.up('ArrowRight');
await page.keyboard.press('Space');
await page.keyboard.press('Escape');
await page.getByRole('button',{name:'Bed Easter egg'}).click();
await page.getByRole('status').waitFor();
await page.waitForTimeout(3200);
await page.setViewportSize({width:390,height:844});
await page.waitForTimeout(3000);
await page.screenshot({path:'preview-mobile.png'});
console.log('Horizontal overflow:',await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth));
console.log('CONSOLE ERRORS',JSON.stringify(errors));
await browser.close();
if(errors.length)process.exitCode=1;
