import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {readFile} from 'node:fs/promises';

const bundle = await build({entryPoints:['lib/typing-game.ts'],bundle:true,write:false,platform:'node',format:'esm'});
const {ROUND_MS,typingPassages,freshTypingRun,enterTypingText,expireTypingRun,typingStats,normalizeTypingChallenge,typingRating} = await import('data:text/javascript;base64,'+Buffer.from(bundle.outputFiles[0].contents).toString('base64'));
assert.equal(ROUND_MS,60000,'sixty-second rounds');
assert.equal(typingRating(0,100,false),'—');
assert.equal(typingRating(19,100,true),'Warming');
assert.equal(typingRating(20,100,true),'Steady');
assert.equal(typingRating(40,100,true),'Quick');
assert.equal(typingRating(60,100,true),'Cracked');
assert.equal(typingRating(90,100,true),'Goated');
assert.equal(typingRating(90,60,true),'Quick','rushing through mistakes lowers the rating');
const empty=freshTypingRun();
assert.equal(typingStats(empty,'Once',999999).remaining,60,'reading does not start the clock');
assert.strictEqual(enterTypingText(empty,'','Once',1000),empty);
let run=enterTypingText(empty,'O','Once',1000);
assert.equal(run.startedAt,1000);assert.equal(run.attempts,1);
run=enterTypingText(run,'Ox','Once',1200);
assert.equal(run.mistakes,1);assert.equal(typingStats(run,'Once',1200).accuracy,50);
run=enterTypingText(run,'O','Once',1400);
assert.equal(run.mistakes,1);assert.equal(run.attempts,2,'deletion is not a new attempt');
run=enterTypingText(run,'Once','Once',2000);
assert.equal(run.finishedAt,2000);assert.equal(run.attempts,5);assert.equal(typingStats(run,'Once',30000).accuracy,80);
assert.equal(typingStats(run,'Once',30000).wpm,48,'finished speed stops changing');
assert.strictEqual(enterTypingText(run,'Oops','Once',3000),run,'finished rounds cannot change');
const started=enterTypingText(empty,'Once ','Once upon a time',0);
assert.equal(expireTypingRun(started,59999).finishedAt,null);
const expired=expireTypingRun(started,69000);
assert.equal(expired.finishedAt,60000,'background timer gaps still stop at exactly sixty seconds');
assert.equal(typingStats(expired,'Once upon a time',999999).wpm,1);
assert.equal(typingStats(expired,'Once upon a time',999999).remaining,0);
assert.equal(enterTypingText(started,'Once upon a time','Once upon a time',60000).text,'Once ','late input cannot change a result');
const wrong=enterTypingText(empty,'Oxxx','Once',100);
assert.equal(wrong.finishedAt,null,'full-length wrong input does not auto-complete');
const fixed=enterTypingText(wrong,'Once','Once',2100);
assert.equal(fixed.finishedAt,2100);assert.equal(fixed.mistakes,3);assert.equal(fixed.attempts,7);
assert.equal(enterTypingText(empty,'it\u2019s','it\'s',100).text,"it's",'smart punctuation works on mobile');
const emoji=enterTypingText(enterTypingText(empty,'g','go 🗿',0),'go 🗿','go 🗿',1000);
assert.equal(typingStats(emoji,'go 🗿',1000).progress,100,'emoji do not shift the remaining character positions');
assert.equal(typingPassages[0].text,'Once upon a time there was a chud in a far away land in Alabama who moved to San Diego, then Providence, Rhode Island then San Francisco.');
assert(typingPassages[1].text.includes('OTTAWA. Memorize that city. Ottawa. Ottawa. Ottawa.'));
assert(typingPassages.every(p=>p.text.length>80&&p.text.length<300));
const ui=await readFile('components/TypingGame.tsx','utf8');
assert(ui.includes('clearInterval(timer)')&&ui.includes('run.startedAt === null || done'),'timer runs only during a round');
assert(ui.includes('onPaste=')&&ui.includes('readOnly={done}')&&ui.includes('aria-describedby='));
assert.equal((ui.match(/<button /g)||[]).length,6,'original story selector, add, retry, next and separate editor controls');
assert(ui.includes('eyebrow="Typing speedrun"')&&ui.includes('aria-label="Add typing challenge"'));
assert(ui.includes('{adding ? <form'),'challenge form replaces the game instead of expanding the popup');
assert(ui.includes('Original typing stories')&&ui.includes('typingPassages.slice(0, 2)')&&!ui.includes('typing-hint'),'original story tabs stay beside add with no visible tutorial');
const css=await readFile('app/typing.css','utf8');
assert(css.includes('height:min(420px,var(--panel-available-height))')&&css.includes('overflow:hidden'),'popup stays within its available frame');
assert(css.includes('repeat(4,minmax(0,1fr))')&&ui.includes('<dt>Rating</dt>'),'four compact statistics including the rating');
assert(!ui.includes('localStorage'),'shared storage replaces browser-only saves');
assert.equal(normalizeTypingChallenge('It\u2019s time.  No cap.'),"It's time. No cap.");
assert(ui.includes('addTypingChallenge(text)')&&ui.includes('finishTypingRound({ id: start.id')&&ui.includes('typing-best'),'shared challenges and small best-score label');
const experience=await readFile('components/Experience.tsx','utf8');
assert(experience.includes("dynamic(() => import('./TypingGame'), { ssr: false })"));
assert(experience.includes("panel==='typing'&&<TypingGame"));
const scene=await readFile('components/Penthouse/Scene.tsx','utf8');assert(scene.includes("onKeyboard={()=>onInteract('typing')}"));
const keyboard=await readFile('components/Penthouse/Workstation.tsx','utf8');
assert(keyboard.includes('event.stopPropagation();setKeyboardHover(false);onKeyboard()'),'keyboard does not bubble into music');
assert(keyboard.includes('keyboard-click-target')&&keyboard.includes('onLaptop()'),'keyboard hit area added, music preserved');
const rig=await readFile('components/Penthouse/CameraRig.tsx','utf8');assert.equal((rig.match(/typing:\{p:/g)||[]).length,2);
console.log('PASS: 60-second timer, first-key start, typo correction and accuracy, WPM, early completion, deadline and delayed input, mobile punctuation, story copy, isolated data, keyboard integration.');
